// Run against an isolated mock preview, never against the user's OpenAI-backed DB.
import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const root = fileURLToPath(new URL('../', import.meta.url));
const require = createRequire(root + 'frontend/package.json');
const { chromium, expect } = require('@playwright/test');
const url = process.env.EXAM_PREVIEW_URL;
assert.ok(url, 'Set EXAM_PREVIEW_URL to an isolated mock preview on LAN HTTP');
const health = await (await fetch(url + '/api/health')).json();
assert.equal(health.provider, 'mock', 'UI smoke test needs an isolated mock preview');
const output = root + 'data/ui-verification';
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
const page = await context.newPage();
const errors = [];
const sourceName = `手順の検証-${Date.now()}.txt`;
const headingName = `目次だけ-${Date.now()}.txt`;
page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto(url);
  await expect(page.getByRole('heading', { name: '今日も、一歩先へ。' })).toBeVisible();
  const secureContext = await page.evaluate(() => ({ secure: isSecureContext, randomUUID: typeof crypto.randomUUID }));
  assert.equal(secureContext.secure, false, 'Must exercise LAN HTTP');
  assert.equal(secureContext.randomUUID, 'undefined');
  await page.getByRole('button', { name: '試験範囲の資料' }).first().click();
  if (await page.locator('.materials-import').getAttribute('open') === null) await page.locator('.materials-import > summary').click();
  await page.getByLabel('資料ファイル').setInputFiles({ name: sourceName, mimeType: 'text/plain', buffer: Buffer.from('個人情報は部門長が管理する。事故が発生した場合は上長へ報告する。記録は所定の場所に保存しなければならない。') });
  await expect(page.getByRole('checkbox', { name: sourceName })).toBeVisible();
  const submit = page.getByRole('button', { name: 'この内容で問題を作成', exact: true });
  await page.getByRole('button', { name: '選択を解除', exact: true }).click();
  await expect(submit).toBeDisabled();
  await page.getByRole('button', { name: 'すべて選択', exact: true }).click();
  await page.getByRole('radio', { name: '単語 用語や数値を答える' }).check();
  await page.getByRole('spinbutton', { name: '目標の問数' }).fill('0');
  await expect(submit).toBeDisabled();
  await page.getByRole('button', { name: '5問', exact: true }).click();
  await expect(submit).toBeEnabled();
  await page.screenshot({ path: output + '/generation-desktop.png', fullPage: true });
  await submit.click();
  await expect(page.getByRole('button', { name: '演習を始める', exact: true })).toBeVisible({ timeout: 30000 });
  await page.getByRole('button', { name: '演習を始める', exact: true }).click();
  await expect(page.getByRole('button', { name: '答え合わせ', exact: true })).toBeVisible();
  await page.reload();
  await page.getByRole('button', { name: '試験範囲の資料' }).first().click();
  if (await page.locator('.materials-import').getAttribute('open') === null) await page.locator('.materials-import > summary').click();
  await page.getByLabel('資料ファイル').setInputFiles({ name: headingName, mimeType: 'text/plain', buffer: Buffer.from('目次') });
  await expect(page.getByRole('checkbox', { name: headingName })).toBeVisible();
  await page.getByRole('button', { name: '選択を解除', exact: true }).click();
  await page.getByRole('checkbox', { name: headingName }).check();
  await submit.click();
  await expect(page.getByRole('heading', { name: '出題に適した問題を作成できませんでした' })).toBeVisible({ timeout: 30000 });
  await page.reload();
  await expect(page.getByRole('heading', { name: '出題に適した問題を作成できませんでした' })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: '試験範囲の資料' }).first().click();
  await page.screenshot({ path: output + '/generation-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'No horizontal page overflow on mobile');
  await page.getByRole('button', { name: 'すべて選択', exact: true }).click();
  await expect(submit).toBeEnabled();
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ desktop: 'passed', mobile: 'passed', lanHttpPractice: 'passed', zeroQuestionCompletionAndReload: 'passed', pageErrors: errors, screenshots: output }));
} finally {
  await context.close();
  await browser.close();
}
